import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Camisa Elegante Tipica",
    description: "Camisa de corte clásico confeccionada en algodón premium. Perfecta para ocasiones formales y casuales.",
    price: 18000,
    category: "Ocasiones Especiales",
    image: "/elegant-dress-shirt.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Blanco", "Azul", "Negro", "Rojo"],
    target: "Hombre",
    sku: "SKU-1001",
  },
  {
    id: "2",
    name: "Vestido Tipico Rosado con Flores Tipicas",
    description: "Vestido con estampado de Flores Tipicas, Ideal para eventos especiales. Confección artesanal con telas de alta calidad.",
    price: 38000,
    category: "Ocasiones Especiales",
    image: "/Vestido tipico Mujer-flores.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1002",
  },
  {
    id: "3",
    name: "Traje Niño Gato Con Botas",
    description: "Traje Ocasion especial, el gato con botas. Confeccionado con tela resistente.",
    price: 28000,
    category: "Ocasiones Especiales",
    image: "/Traje-ElGato-Con-Botas.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1003",
  },
  {
    id: "4",
    name: "Blusa Pura Vida",
    description: "Blusa casual frase costarricense. Pieza única y especial.",
    price: 15000,
    category: "Ocasiones Especiales",
    image: "/Blusa-PuraVida.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Blanco", "Negro", "Azul"],
    target: "Mujer",
    sku: "SKU-1004",
  },
  {
    id: "5",
    name: "Blusa Seda",
    description: "Blusa Elegante de material Seda. Confección de alta calidad.",
    price: 20000,
    category: "Blusas",
    image: "/Blusa-Blanca-Seda.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Blanca","Azul","Negra"],
    target: "Mujer",
    sku: "SKU-1005",
  },
  {
    id: "6",
    name: "Camisa Estilo Tribal",
    description: "Camisa Estilo Tribal, fresca y cómoda. Perfecta para el clima tropical costarricense.",
    price: 22000,
    category: "Camisas",
    image: "/Camisa-Casual-Tribal.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Hombre",
    sku: "SKU-1006",
  },
  {
    id: "7",
    name: "Vestido Navideño",
    description: "Vestido Navideño de mujer. Ideal para eventos y celebraciones de temporada.",
    price: 45000,
    category: "Ocasiones Especiales",
    image: "/Vestido-Navideño.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1007",
  },
  {
    id: "8",
    name: "Conjunto Niño",
    description: "Conjunto Niño Sport.",
    price: 18000,
    category: "Conjuntos",
    image: "/Conjunto-Niño.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Negro","Rojo","Azul","Blanco"],
    target: "Niño",
    sku: "SKU-1008",
  },
  {
    id: "9",
    name: "Pijama Mujer Winnie the Pooh",
    description: "Pijama Mujer para las noches frescas. Diseño de personajes Disney, super versátil.",
    price: 26500,
    category: "Pijama",
    image: "/Pijama-Mujer.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1009",
  },
  {
    id: "10",
    name: "Vestido Tipico Limonense Colorido",
    description: "Vestido Tipico Limonense Colorido y Elegante. Ideal para Celebraciones especiales.",
    price: 37000,
    category: "Ocasiones Especiales",
    image: "/Vestido-Tipico-Limonense.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1010",
  },
  {
    id: "11",
    name: "Disfraz Pez",
    description: "Disfraz Pez, Divertido, perfecto para eventos como fiestas o actividades familiares.",
    price: 27000,
    category: "Ocasiones Especiales",
    image: "/DisfrazPez-Nino.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1011",
  },
  {
    id: "12",
    name: "Pijama Navideña",
    description: "Camisa con estampado tropical, ideal para el verano costarricense.",
    price: 18000,
    category: "Ocasiones Especiales",
    image: "/Pijama-Navidena.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1012",
  },
  {
    id: "13",
    name: "Pijama Navideña Mickey con Verde",
    description: "Pijama Navideña Mickey con Verde. Perfecto para actividades navideñas.",
    price: 15000,
    category: "Pijama",
    image: "/Pijama-NavidenaMickey-Verde.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1013",
  },
  {
    id: "14",
    name: "Pijama Navideña Mickey con Roja",
    description: "Pijama Navideña Mickey con Roja. Perfecto para actividades navideñas.",
    price: 15000,
    category: "Pijama",
    image: "/Pijama-NavidenaMickey-Roja.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niña",
    sku: "SKU-1014",
  },
  {
    id: "15",
    name: "Traje Navideño Niño",
    description: "Traje Navideño Niño, ideal para actividades navideñas.",
    price: 15000,
    category: "Ocasiones Especiales",
    image: "/Traje-Navideno-Niño.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1015",
  },
  {
    id: "16",
    name: "Pantalones Cargo de Hombre",
    description: "Pantalones Cargo de Hombre, ideal para actividades casuales.",
    price: 15000,
    category: "Pantalones",
    image: "/Pantalones-Cargo-Hombre.png",
    sizes: ["32","34","36","38","40","42"],
    colors: ["Verde", "Negro", "Azul", "Rojo"],
    target: "Hombre",
    sku: "SKU-1016",
  },
  {
    id: "17",
    name: "Vestido Tipico Blanco Con Orquideas",
    description: "Vestido con estampado color blanco con Orquideas, Ideal para eventos especiales tipicos. Confección artesanal con telas de alta calidad.",
    price: 34000,
    category: "Ocasiones Especiales",
    image: "/Vestido-tipico-blanco orquideas.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1017",
  },
  {
    id: "18",
    name: "Vestido Tipico Orquideas Borde Morado",
    description: "Vestido con estampado de Orquideas, Ideal para eventos especiales tipicos. Confección artesanal con telas de alta calidad.",
    price: 35000,
    category: "Ocasiones Especiales",
    image: "/Vestido tipico Mujer-Orquideas.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1018",
  },
  {
    id: "19",
    name: "Vestido Tipico Ruedas de Carreta",
    description: "Vestido con estampado de Ruedas de Carreta, Ideal para eventos especiales tipicos. Confección artesanal con telas de alta calidad.",
    price: 39000,
    category: "Ocasiones Especiales",
    image: "/Vestido Tipico Ruedas de Carreta.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1019",
  },
  {
    id: "20",
    name: "Blusa Tipica Roja",
    description: "Blusa Tipica Roja. Confección artesanal con telas de alta calidad.",
    price: 12000,
    category: "Ocasiones Especiales",
    image: "/BlusaTipica Roja.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1020",
  },
  {
    id: "21",
    name: "Vestido Tipico Rojo",
    description: "Vestido Tipico Rojo. Confección artesanal con telas de alta calidad.",
    price: 20000,
    category: "Vestido",
    image: "/Vestido Tipico Rojo.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1021",
  },
  {
    id: "22",
    name: "Traje Limonense Niño",
    description: "Traje Limonense Niño. Confección artesanal con telas de alta calidad.",
    price: 19500,
    category: "Ocasiones Especiales",
    image: "/TrajeLimonense Nino.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1022",
  },
  {
    id: "23",
    name: "Traje Campesino Niño",
    description: "Traje Campesino Niño. Confección artesanal con telas de alta calidad.",
    price: 17500,
    category: "Ocasiones Especiales",
    image: "/Traje Campesino Niño.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1023",
  },
  {
    id: "24",
    name: "Traje Pokemon Scyther",
    description: "Traje Pokemon Scyther Niño. Disfraz de alta calidad, Confección artesanal con telas de alta calidad.",
    price: 20500,
    category: "Ocasiones Especiales",
    image: "/Traje Pokemon Scyther.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1024",
  },
  {
    id: "25",
    name: "Traje Campesino Niño Pañuelo Rojo",
    description: "Traje Campesino Niño Blanco. Confección artesanal con telas de alta calidad.",
    price: 18500,
    category: "Ocasiones Especiales",
    image: "/Traje Campesino Niño Pañuelo Rojo.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niño",
    sku: "SKU-1025",
  },
  {
    id: "26",
    name: "Vestido Ballet Niña",
    description: "Vestido Ballet Niña. Confección artesanal con telas de alta calidad.",
    price: 19000,
    category: "Vestido",
    image: "/Vestido Ballet Niña.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niña",
    sku: "SKU-1026",
  },
  {
    id: "27",
    name: "Vestido Limonenese Colorido",
    description: "Vestido Limonenese Colorido. Confección artesanal con telas de alta calidad.",
    price: 27000,
    category: "Ocasiones Especiales",
    image: "/Vestido Limonenese Colorido.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1027",
  },
  {
    id: "28",
    name: "Pijama Capibara Rosada",
    description: "Pijama Capibara Rosada. Confección artesanal con telas de alta calidad.",
    price: 13000,
    category: "Pijama",
    image: "/Pijama Capibara.png",
    sizes: ["XS","S","M","L","XL"],
    colors: ["Color Unico"],
    target: "Mujer",
    sku: "SKU-1028",
  },
  {
    id: "29",
    name: "Traje Tipico Campesina Niña",
    description: "Traje Tipico Campesina Niña. Ideal para eventos especiales tipicos. Confección artesanal con telas de alta calidad.",
    price: 27000,
    category: "Ocasiones Especiales",
    image: "/Traje Tipico Campesina NiñaAzulRojo.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niña",
    sku: "SKU-1029",
  },
  {
    id: "30",
    name: "Pijama Niña Celeste",
    description: "Pijama Niña Celeste. Confección artesanal con telas de alta calidad.",
    price: 13500,
    category: "Pijama",
    image: "/Pijama Nina Celeste.png",
    sizes: ["4","6","8","10","12","14","16"],
    colors: ["Color Unico"],
    target: "Niña",
    sku: "SKU-1030",
  },
  {
  id: "31",
  name: "Pijama Grinch Niña",
  description: "Pijama Grinch Niña. Confección artesanal con telas de alta calidad.",
  price: 17500,
  category: "Pijama",
  image: "/Pijama Navidena El Grinch.png",
  sizes: ["4","6","8","10","12","14","16"],
  colors: ["Color Unico"],
  target: "Niña",
  sku: "SKU-1031",
},
{
  id: "32",
  name: "Traje Tipico Campesina Perezoso",
  description: "Traje Tipico Campesina Perezoso. Ideal para eventos especiales tipicos. Confección artesanal con telas de alta calidad.",
  price: 33000,
  category: "Ocasiones Especiales",
  image: "/Traje Tipico Campesina Perezoso.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Mujer",
  sku: "SKU-1032",
},
{
  id: "33",
  name: "Blusa Tipica Morada con Blanco",
  description: "Blusa Tipica Morada con Blanco.png. Ideal para eventos especiales tipicos. Confección artesanal con telas de alta calidad.",
  price: 22000,
  category: "Ocasiones Especiales",
  image: "/Blusa Tipica Morada con Blanco.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Mujer",
  sku: "SKU-1033",
},
{
  id: "34",
  name: "Camiseta Dichos Ticos (Mea, Jeta, SiaTonto, queMADRE, Q'Chiva)",
  description: "Camiseta Dichos Ticos (Mea, Jeta, SiaTonto, queMADRE, Q'Chiva). Confección artesanal con telas de alta calidad.",
  price: 12000,
  category: "Camiseta",
  image: "/Camiseta Dichos Ticos Mes, Jeta,SiaTonto,queMADRE.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1034",
},
{
  id: "35",
  name: "Boxer Dichos Ticos (Mea, Jeta, SiaTonto, queMADRE, Q'Chiva)",
  description: "Boxer Dichos Ticos (Mea, Jeta, SiaTonto, queMADRE, Q'Chiva). Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/Boxer Dichos Ticos (Mea, Jeta, SiaTonto, queMADRE, Q'Chiva).png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1035",
},
{
  id: "36",
  name: "Boxer Nike Naranja",
  description: "Boxer Nike Naranja. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/BoxerNikeNaranja.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1036",
},
{
  id: "37",
  name: "Boxer Nike Amarillo",
  description: "Boxer Nike Amarillo. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/BoxerNikeAmarillo.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1037",
},
{
  id: "38",
  name: "Boxer Volcom",
  description: "Boxer Volcom. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/BoxerVolcom.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1038",
},
{
  id: "39",
  name: "Boxer Tommy Rojo",
  description: "Boxer Tommy Rojo. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/BoxerTommyRojo.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1039",
},
{
  id: "40",
  name: "Boxer Volcom Consolas",
  description: "Boxer Volcom Consolas. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/Boxer Volcom Consolas.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1040",
},
{
  id: "41",
  name: "Boxer Adidas Azul",
  description: "Boxer Adidas Azul. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/BoxerAdidas Azul.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1041",
},
{
  id: "42",
  name: "Boxer Saprisa",
  description: "Boxer Saprisa. Confección artesanal con telas de alta calidad.",
  price: 8000,
  category: "Boxer",
  image: "/BoxerSaprisa.png",
  sizes: ["XS","S","M","L","XL"],
  colors: ["Color Unico"],
  target: "Hombre",
  sku: "SKU-1042",
},
{
  id: "43",
  name: "Pijama Niña Rosada-Azul",
  description: "Pijama Niña Rosada-Azul. Confección artesanal con telas de alta calidad.",
  price: 14000,
  category: "Pijama",
  image: "/Pijama Niña Rosada-Azul.png",
  sizes: ["4","6","8","10","12","14","16"],
  colors: ["Color Unico"],
  target: "Niña",
  sku: "SKU-1043",
},
{
  id: "44",
  name: "Traje Policia Niño",
  description: "Traje Policia Niño. Ideal para Actividades Especiales, Fiestas, Eventos, Hallowen, etc",
  price: 18000,
  category: "Ocasiones Especiales",
  image: "/Traje Policia Niño.png",
  sizes: ["4","6","8","10","12","14","16"],
  colors: ["Color Unico"],
  target: "Niño",
  sku: "SKU-1044",
},
{
  id: "45",
  name: "Gnomo Rojo",
  description: "Gnomo Rojo Decoración para Navidad o cualquier momento del Año.",
  price: 9000,
  category: "Decoración",
  image: "/Gnomo Rojo Decoracion.png",
  sizes: ["Diseño Unico"],
  colors: ["Color Unico"],
  target: "Decoración",
  sku: "SKU-1045",
},
{
  id: "46",
  name: "Pañuelos Tipicos, Cobertores para Almohadones",
  description: "Pañuelos Tipicos Cobertores para Almohadones para Fiestras Patrias o Cualquier Momento del Año.",
  price: 8000,
  category: "Decoración",
  image: "/Pañuelos Tipicos para Almohadones.png",
  sizes: ["Diseño Unico"],
  colors: ["Color Unico"],
  target: "Decoración",
  sku: "SKU-1046",
},
{
  id: "47",
  name: "Bolso Mafalda",
  description: "Pañuelos Tipicos Cobertores para Almohadones para Fiestras Patrias o Cualquier Momento del Año.",
  price: 18000,
  category: "Decoración",
  image: "/Bolso Mafalda.png",
  sizes: ["Diseño Unico"],
  colors: ["Color Unico"],
  target: "Decoración",
  sku: "SKU-1047",
},
{
  id: "48",
  name: "Pijama Miña Estampado con Osos Morados",
  description: "Pijama Miña Osos Morados. Perfecto para los dias y noches frias.",
  price: 14000,
  category: "Pijama",
  image: "/Pijama de niña Osos Morados.png",
  sizes: ["4","6","8","10","12","14","16"],
  colors: ["Color Unico"],
  target: "Niña",
  sku: "SKU-1048",
},
{
  id: "49",
  name: "Pijama Niña Estampado de Bambi",
  description: "Pijama Niña Estampado de Bambi. Perfecto para los dias y noches frias.",
  price: 14000,
  category: "Pijama",
  image: "/Pijama de niña Bambi.png",
  sizes: ["4","6","8","10","12","14","16"],
  colors: ["Color Unico"],
  target: "Niña",
  sku: "SKU-1049",
},
]